// src/app/sections/footer.component.ts
import { Component } from "@angular/core";

@Component({
  selector: "app-footer",
  standalone: true,
  template: `
    <footer class="border-t border-border/60 py-8">
      <div class="container mx-auto px-6 text-center text-sm text-muted-foreground">
        © 2024 Pavan Kumar Reddy. All rights reserved.
      </div>
    </footer>
  `,
})
export class FooterComponent {}

// src/components/Footer.tsx
import { motion } from "framer-motion";

const Footer = () => {
  const currentYear = new Date().getFullYear();

  return (
    <footer className="py-8 border-t border-border">
      <div className="container mx-auto px-6">
        <motion.div
          initial={{ opacity: 0 }}
          whileInView={{ opacity: 1 }}
          transition={{ duration: 0.6 }}
          viewport={{ once: true }}
          className="flex flex-col md:flex-row justify-between items-center gap-4"
        >
          <p className="text-sm text-muted-foreground">
            © {currentYear} Pavan Kumar Reddy. All rights reserved.
          </p>
          <p className="text-sm text-muted-foreground">
            Built with{" "}
            <span className="text-primary">♥</span>
          </p>
        </motion.div>
      </div>
    </footer>
  );
};

export default Footer;
