// src/components/HeroSection.tsx
import { motion } from "framer-motion";
import { Linkedin, Instagram, MessageCircle } from "lucide-react";
import pavanImage from "@/assets/pavan.png";

const socialLinks = [
  { icon: Linkedin, href: "https://www.linkedin.com/in/ypavan-net/", label: "LinkedIn" },
  { icon: Instagram, href: "https://www.instagram.com/y.pavan.kr/", label: "Instagram" },
  { icon: MessageCircle, href: "https://wa.me/+919148283004", label: "WhatsApp" },
];

const HeroSection = () => {
  return (
    <section className="relative min-h-screen flex items-center justify-center overflow-hidden">
      {/* Background Gradient */}
      <div 
        className="absolute inset-0"
        style={{ background: "var(--gradient-hero)" }}
      />
      
      {/* Animated Orbs */}
      <div className="absolute top-1/4 left-1/4 w-96 h-96 bg-primary/10 rounded-full blur-3xl animate-pulse-glow" />
      <div className="absolute bottom-1/4 right-1/4 w-80 h-80 bg-accent/10 rounded-full blur-3xl animate-pulse-glow" style={{ animationDelay: "1.5s" }} />

      <div className="container mx-auto px-6 relative z-10">
        <div className="flex flex-col items-center text-center">
          {/* Profile Image */}
          <motion.div
            initial={{ scale: 0, opacity: 0 }}
            animate={{ scale: 1, opacity: 1 }}
            transition={{ duration: 0.6, ease: "easeOut" }}
            className="relative mb-8"
          >
            <div className="w-40 h-40 md:w-48 md:h-48 rounded-full overflow-hidden border-2 border-primary/30 p-1 card-glow">
              <img
                src={pavanImage}
                alt="Pavan Kumar"
                className="w-full h-full rounded-full object-cover"
              />
            </div>
            {/* Decorative Ring */}
            <div className="absolute inset-0 rounded-full border border-primary/20 animate-float" style={{ transform: "scale(1.2)" }} />
          </motion.div>

          {/* Name */}
          <motion.h1
            initial={{ y: 30, opacity: 0 }}
            animate={{ y: 0, opacity: 1 }}
            transition={{ duration: 0.6, delay: 0.2 }}
            className="font-heading text-4xl md:text-6xl lg:text-7xl font-bold mb-4"
          >
            <span className="text-foreground">Pavan Kumar</span>{" "}
            <span className="text-gradient">Reddy</span>
          </motion.h1>

          {/* Title */}
          <motion.div
            initial={{ y: 30, opacity: 0 }}
            animate={{ y: 0, opacity: 1 }}
            transition={{ duration: 0.6, delay: 0.3 }}
            className="mb-6"
          >
            <p className="text-xl md:text-2xl text-muted-foreground font-medium">
              Senior Software Engineer
            </p>
            <p className="text-primary font-heading font-semibold mt-1">
              Microsoft .NET Technologies
            </p>
          </motion.div>

          {/* Social Links */}
          <motion.div
            initial={{ y: 30, opacity: 0 }}
            animate={{ y: 0, opacity: 1 }}
            transition={{ duration: 0.6, delay: 0.4 }}
            className="flex gap-4"
          >
            {socialLinks.map(({ icon: Icon, href, label }) => (
              <a
                key={label}
                href={href}
                target="_blank"
                rel="noopener noreferrer"
                className="social-icon"
                aria-label={label}
              >
                <Icon size={20} />
              </a>
            ))}
          </motion.div>

          {/* Scroll Indicator */}
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            transition={{ duration: 0.6, delay: 0.8 }}
            className="absolute bottom-8 left-1/2 -translate-x-1/2"
          >
            <div className="w-6 h-10 rounded-full border-2 border-muted-foreground/30 flex justify-center pt-2">
              <motion.div
                animate={{ y: [0, 8, 0] }}
                transition={{ duration: 1.5, repeat: Infinity }}
                className="w-1.5 h-1.5 rounded-full bg-primary"
              />
            </div>
          </motion.div>
        </div>
      </div>
    </section>
  );
};

export default HeroSection;

// src/app/sections/hero-section.component.ts
import { Component } from "@angular/core";

@Component({
  selector: "app-hero-section",
  standalone: true,
  template: `
    <section class="relative flex min-h-screen items-center justify-center overflow-hidden">
      <div class="absolute inset-0" style="background: var(--gradient-hero)"></div>
      <div class="absolute top-1/4 left-1/4 h-96 w-96 rounded-full bg-primary/10 blur-3xl animate-pulse-glow"></div>
      <div
        class="absolute bottom-1/4 right-1/4 h-80 w-80 rounded-full bg-accent/10 blur-3xl animate-pulse-glow"
        style="animation-delay: 1.5s"
      ></div>

      <div class="container relative z-10 mx-auto px-6">
        <div class="flex flex-col items-center text-center">
          <div class="relative mb-8">
            <div class="card-glow h-40 w-40 overflow-hidden rounded-full border-2 border-primary/30 p-1 md:h-48 md:w-48">
              <img
                src="assets/pavan.png"
                alt="Pavan Kumar"
                class="h-full w-full rounded-full object-cover"
              />
            </div>
            <div class="absolute inset-0 rounded-full border border-primary/20 animate-float" style="transform: scale(1.2)"></div>
          </div>

          <h1 class="font-heading mb-4 text-4xl font-bold md:text-6xl lg:text-7xl">
            <span class="text-foreground">Pavan Kumar</span>
            <span class="text-gradient">Reddy</span>
          </h1>

          <div class="mb-6">
            <p class="text-xl font-medium text-muted-foreground md:text-2xl">Senior Software Engineer</p>
            <p class="mt-1 font-heading font-semibold text-primary">Microsoft .NET Technologies</p>
          </div>

          <div class="flex gap-4">
            <a
              class="social-icon"
              href="https://www.linkedin.com/in/ypavan-net/"
              target="_blank"
              rel="noopener noreferrer"
            >
              LinkedIn
            </a>
            <a
              class="social-icon"
              href="https://www.instagram.com/y.pavan.kr/"
              target="_blank"
              rel="noopener noreferrer"
            >
              Instagram
            </a>
            <a class="social-icon" href="https://wa.me/+919148283004" target="_blank" rel="noopener noreferrer">
              WhatsApp
            </a>
          </div>
        </div>
      </div>
    </section>
  `,
})
export class HeroSectionComponent {}
